# Auto-Scaling Policies Configuration
# Intelligent scaling based on metrics and patterns

autoscaling:
  # Enable auto-scaling
  enabled: ${AUTOSCALING_ENABLED:-true}
  
  # Scaling provider
  provider: "${AUTOSCALING_PROVIDER:-kubernetes}"  # kubernetes, aws, gcp, azure, docker-swarm
  
  # CPU-based scaling
  cpu:
    # Enable CPU-based scaling
    enabled: true
    
    # Scale up policies
    scaleUp:
      # CPU threshold for scaling up
      threshold: 70             # percentage
      
      # Evaluation periods
      evaluationPeriods: 2      # consecutive periods above threshold
      
      # Period duration
      periodSeconds: 60         # seconds
      
      # Scale up action
      action:
        type: "increment"       # increment, percentage, or exact
        value: 1                # add 1 instance
        
      # Cooldown period
      cooldown: 300             # 5 minutes in seconds
      
    # Scale down policies
    scaleDown:
      # CPU threshold for scaling down
      threshold: 30             # percentage
      
      # Evaluation periods
      evaluationPeriods: 5      # consecutive periods below threshold
      
      # Period duration
      periodSeconds: 60         # seconds
      
      # Scale down action
      action:
        type: "decrement"       # decrement, percentage, or exact
        value: 1                # remove 1 instance
        
      # Cooldown period
      cooldown: 600             # 10 minutes in seconds
      
  # Memory-based scaling
  memory:
    # Enable memory-based scaling
    enabled: true
    
    # Scale up policies
    scaleUp:
      threshold: 75             # percentage
      evaluationPeriods: 2
      periodSeconds: 60
      
      action:
        type: "increment"
        value: 1
        
      cooldown: 300
      
    # Scale down policies
    scaleDown:
      threshold: 40             # percentage
      evaluationPeriods: 5
      periodSeconds: 60
      
      action:
        type: "decrement"
        value: 1
        
      cooldown: 600
      
  # Request-based scaling
  requests:
    # Enable request-based scaling
    enabled: true
    
    # Scale up policies
    scaleUp:
      # Requests per second threshold
      threshold: 1000           # requests per second
      
      evaluationPeriods: 2
      periodSeconds: 60
      
      action:
        type: "increment"
        value: 2                # add 2 instances for traffic spike
        
      cooldown: 180             # 3 minutes
      
    # Scale down policies
    scaleDown:
      threshold: 200            # requests per second
      evaluationPeriods: 10
      periodSeconds: 60
      
      action:
        type: "decrement"
        value: 1
        
      cooldown: 600
      
  # Response time-based scaling
  responseTime:
    # Enable response time-based scaling
    enabled: true
    
    # Scale up policies
    scaleUp:
      # P95 response time threshold
      threshold: 2000           # milliseconds
      
      evaluationPeriods: 3
      periodSeconds: 60
      
      action:
        type: "increment"
        value: 1
        
      cooldown: 300
      
  # Custom metrics scaling
  custom:
    # Enable custom metrics scaling
    enabled: true
    
    metrics:
      # Queue depth
      - name: "queue_depth"
        scaleUp:
          threshold: 100
          evaluationPeriods: 2
          periodSeconds: 30
          
          action:
            type: "increment"
            value: 2
            
          cooldown: 120
          
        scaleDown:
          threshold: 10
          evaluationPeriods: 5
          periodSeconds: 60
          
          action:
            type: "decrement"
            value: 1
            
          cooldown: 300
          
      # Database connections
      - name: "db_connections"
        scaleUp:
          threshold: 80         # percentage of max connections
          evaluationPeriods: 2
          periodSeconds: 60
          
          action:
            type: "increment"
            value: 1
            
          cooldown: 300
          
  # Instance configuration
  instances:
    # Minimum instances (always running)
    min: ${MIN_INSTANCES:-2}
    
    # Maximum instances (scale limit)
    max: ${MAX_INSTANCES:-20}
    
    # Desired capacity (initial)
    desired: ${DESIRED_INSTANCES:-3}
    
    # Instance warm-up time
    warmupTime: 120             # 2 minutes in seconds
    
    # Health check grace period
    healthCheckGracePeriod: 60  # 1 minute in seconds
    
  # Scaling behavior
  behavior:
    # Scale up behavior
    scaleUp:
      # Stabilization window
      stabilizationWindow: 0    # seconds (0 = disabled)
      
      # Select policy
      selectPolicy: "max"       # max, min, or disabled
      
      # Max scale up rate
      policies:
        - type: "pods"
          value: 4              # max 4 pods at once
          periodSeconds: 60
          
        - type: "percent"
          value: 100            # max 100% increase
          periodSeconds: 60
          
    # Scale down behavior
    scaleDown:
      # Stabilization window
      stabilizationWindow: 300  # 5 minutes in seconds
      
      # Select policy
      selectPolicy: "min"       # max, min, or disabled
      
      # Max scale down rate
      policies:
        - type: "pods"
          value: 1              # max 1 pod at once
          periodSeconds: 60
          
        - type: "percent"
          value: 10             # max 10% decrease
          periodSeconds: 60
          
  # Predictive scaling
  predictive:
    # Enable predictive scaling
    enabled: ${PREDICTIVE_SCALING_ENABLED:-true}
    
    # Machine learning model
    model: "time_series"        # time_series, regression, or neural_network
    
    # Training data
    training:
      # Historical data period
      period: 30                # days
      
      # Minimum data points
      minDataPoints: 100
      
      # Retrain frequency
      retrainInterval: 86400    # 24 hours in seconds
      
    # Prediction
    prediction:
      # Forecast horizon
      horizon: 3600             # 1 hour in seconds
      
      # Update frequency
      updateInterval: 300       # 5 minutes in seconds
      
      # Confidence threshold
      confidence: 0.8           # 80%
      
    # Patterns to recognize
    patterns:
      # Daily patterns
      - type: "daily"
        enabled: true
        peaks:
          - time: "09:00"       # morning peak
            multiplier: 1.5
            
          - time: "14:00"       # afternoon peak
            multiplier: 1.3
            
          - time: "20:00"       # evening peak
            multiplier: 1.4
            
      # Weekly patterns
      - type: "weekly"
        enabled: true
        peaks:
          - day: "monday"
            multiplier: 1.2
            
          - day: "friday"
            multiplier: 1.1
            
      # Seasonal patterns
      - type: "seasonal"
        enabled: true
        months:
          - month: "december"
            multiplier: 1.5     # holiday traffic
            
      # Special events
      - type: "events"
        enabled: true
        events:
          - name: "black_friday"
            date: "2024-11-29"
            multiplier: 3.0
            
          - name: "cyber_monday"
            date: "2024-12-02"
            multiplier: 2.5
            
    # Pre-scaling
    preScale:
      # Scale up before predicted load
      enabled: true
      
      # Lead time
      leadTime: 600             # 10 minutes in seconds
      
      # Buffer percentage
      buffer: 20                # 20% above prediction
      
  # Scheduled scaling
  scheduled:
    # Enable scheduled scaling
    enabled: true
    
    schedules:
      # Business hours scaling
      - name: "business_hours"
        enabled: true
        
        # Cron expression (Mon-Fri 9am-5pm)
        scaleUp:
          cron: "0 9 * * 1-5"
          timezone: "America/New_York"
          minInstances: 5
          
        scaleDown:
          cron: "0 17 * * 1-5"
          timezone: "America/New_York"
          minInstances: 2
          
      # Weekend scaling
      - name: "weekend"
        enabled: true
        
        scaleDown:
          cron: "0 0 * * 6"     # Saturday midnight
          minInstances: 1
          
        scaleUp:
          cron: "0 0 * * 1"     # Monday midnight
          minInstances: 3
          
      # Holiday scaling
      - name: "holidays"
        enabled: false
        dates:
          - date: "2024-12-25"
            minInstances: 1
            
  # Target tracking
  targetTracking:
    # Enable target tracking
    enabled: true
    
    # Target metrics
    targets:
      # CPU utilization target
      - metric: "cpu"
        targetValue: 50         # percentage
        
      # Memory utilization target
      - metric: "memory"
        targetValue: 60         # percentage
        
      # Request count per target
      - metric: "request_count_per_target"
        targetValue: 1000       # requests per instance
        
  # Monitoring and alerts
  monitoring:
    # Enable monitoring
    enabled: true
    
    # Metrics to collect
    metrics:
      - "current_instances"
      - "desired_instances"
      - "scaling_activity"
      - "cpu_utilization"
      - "memory_utilization"
      - "request_rate"
      
    # Scaling events
    events:
      log: true
      
      # Event types
      types:
        - "scale_up"
        - "scale_down"
        - "instance_launch"
        - "instance_terminate"
        - "health_check_failure"
        
    # Alerts
    alerts:
      - event: "scale_up_failed"
        severity: "critical"
        action: "notify"
        
      - event: "max_instances_reached"
        severity: "warning"
        action: "notify"
        
      - metric: "scaling_frequency"
        threshold: 10           # per hour
        operator: "greater_than"
        severity: "warning"
        action: "notify"
        message: "Potential flapping detected"
        
  # Cost optimization
  cost:
    # Enable cost optimization
    enabled: true
    
    # Cost constraints
    constraints:
      # Maximum hourly cost
      maxHourlyCost: 100        # USD
      
      # Maximum monthly cost
      maxMonthlyCost: 50000     # USD
      
    # Cost-aware scaling
    costAware:
      enabled: true
      
      # Prefer smaller instances
      preferSmaller: true
      
      # Use spot instances when possible
      useSpot: true
      spotPercentage: 70        # 70% spot, 30% on-demand
      
    # Budget alerts
    budgetAlerts:
      - threshold: 0.8          # 80% of budget
        action: "notify"
        
      - threshold: 0.95         # 95% of budget
        action: "restrict_scaling"
        
# Kubernetes HPA configuration
kubernetes:
  hpa:
    # API version
    apiVersion: "autoscaling/v2"
    
    # Metrics
    metrics:
      - type: "Resource"
        resource:
          name: "cpu"
          target:
            type: "Utilization"
            averageUtilization: 70
            
      - type: "Resource"
        resource:
          name: "memory"
          target:
            type: "Utilization"
            averageUtilization: 75
            
      - type: "Pods"
        pods:
          metric:
            name: "http_requests_per_second"
          target:
            type: "AverageValue"
            averageValue: "1000"
            
    # Behavior
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: "Percent"
            value: 10
            periodSeconds: 60
            
          - type: "Pods"
            value: 1
            periodSeconds: 60
            
      scaleUp:
        stabilizationWindowSeconds: 0
        policies:
          - type: "Percent"
            value: 100
            periodSeconds: 60
            
          - type: "Pods"
            value: 4
            periodSeconds: 60
            
# AWS Auto Scaling configuration
aws:
  autoScaling:
    # Launch template
    launchTemplate:
      id: "${AWS_LAUNCH_TEMPLATE_ID}"
      version: "${AWS_LAUNCH_TEMPLATE_VERSION:-$Latest}"
      
    # Target groups
    targetGroups:
      - "${AWS_TARGET_GROUP_ARN}"
      
    # Health check
    healthCheckType: "ELB"      # EC2 or ELB
    healthCheckGracePeriod: 300
    
    # Scaling policies
    policies:
      - name: "cpu-scale-up"
        policyType: "TargetTrackingScaling"
        targetValue: 70
        metricType: "ASGAverageCPUUtilization"
        
      - name: "request-count-scale"
        policyType: "TargetTrackingScaling"
        targetValue: 1000
        metricType: "ALBRequestCountPerTarget"
        
# Environment-specific overrides
environments:
  development:
    autoscaling:
      enabled: false
      instances:
        min: 1
        max: 2
        desired: 1
        
  staging:
    autoscaling:
      enabled: true
      instances:
        min: 1
        max: 5
        desired: 2
      predictive:
        enabled: false
        
  production:
    autoscaling:
      enabled: true
      instances:
        min: 3
        max: 20
        desired: 5
      predictive:
        enabled: true
      scheduled:
        enabled: true
